### ISSUE TITLE
access访问权限设置也失效了

### ISSUE THREAD

**Issue by wxq851685279** [fangzhengjin/PanelTabs#3]
![image](https://user-images.githubusercontent.com/29041799/136698635-4720289e-5379-4f67-b7b9-c41912a2ffc2.png)

**Comment by fangzhengjin** [comment]
换成插件&nbsp;umi-plugin-panel-tabs，或者参照插件自定义一个wrapper就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月10日(周日) 晚上9:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/PanelTabs] access访问权限设置也失效了 (#3)




 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
